export let categories = [
  {
    id: "clf873aye00003572w4s3zzfg",
    name: "Молочные продукты и яйцо",
    type: "category",
    image: "https://codeine.tech/images/category/milk.jpg",
    slug: "molochnie-producti-i-yaizo",
    order: 1,
  },
  {
    id: "clf873aye00013572bre1w046",
    name: "Хлеб и выпечка",
    type: "category",
    image: "https://codeine.tech/images/category/bread.jpg",
    slug: "hleb-i-vipechka",
    order: 2,
  },
  {
    id: "clf873aye00033572voyqzmp4",
    name: "Овощи и фрукты",
    type: "category",
    image: "https://codeine.tech/images/category/fruits.jpg",
    slug: "ovoshi-i-frukti",
    order: 3,
  },
  {
    id: "clf873ayf002r3572xnqxwj06",
    name: "Замороженные продукты",
    type: "category",
    image: "https://codeine.tech/images/category/frozen.jpg",
    slug: "zamorojennie-producti",
    order: 4,
  },
  {
    id: "clf873aye002f35726sn7c9bi",
    name: "Любимые напитки и снеки",
    type: "category",
    image: "https://codeine.tech/images/category/drinks.jpg",
    slug: "lubimie-napitki-i-sneki",
    order: 5,
  },
  {
    id: "clf873aye002c3572ggqoxd0o",
    name: "Торты и пирожные",
    type: "category",
    image: "https://codeine.tech/images/category/candy.jpg",
    slug: "totri-i-pirojnie",
    order: 6,
  },
  {
    id: "clf873aye002a3572sztc7o9h",
    name: "Чай, кофе",
    type: "category",
    image: "https://codeine.tech/images/category/tea.jpg",
    slug: "chai-kofe",
    order: 7,
  },
  {
    id: "clf873aye0029357261w2xlvl",
    name: "Бакалея",
    type: "category",
    image: "https://codeine.tech/images/category/grocery.jpg",
    slug: "bakaleya",
    order: 8,
  },
  {
    id: "clf873aye00283572iroskiec",
    name: "Здоровое питание",
    type: "category",
    image: "https://codeine.tech/images/category/healthy.jpg",
    slug: "zdorovoe-pitanie",
    order: 9,
  },
  {
    id: "clf873aye0027357286kjxx7a",
    name: "Зоотовары",
    type: "category",
    image: "https://codeine.tech/images/category/pets.jpg",
    slug: "zootovari",
    order: 10,
  },
  {
    id: "clf873aye001g3572uxljtj1d",
    name: "Детское питание",
    type: "category",
    image: "https://codeine.tech/images/category/children.jpg",
    slug: "detskoe-pitanie",
    order: 11,
  },
  {
    id: "clf873aye001f3572oo5ch6gm",
    name: "Мясо и птица",
    type: "category",
    image: "https://codeine.tech/images/category/meat.jpg",
    slug: "myaso-i-ptica",
    order: 12,
  },
  {
    id: "clf873aye00053572mfwlrdl6",
    name: "Непродовольственные товары",
    type: "category",
    image: "https://codeine.tech/images/category/non-food.jpg",
    slug: "neprodovolstvennie-tovari",
    order: 13,
  },
];
